profile:
  default: website

editor_options:
  chunk_output_type: console

editor:
  markdown:
    wrap: 72

execute:
  warning: false
  message: false
  cache: false
  freeze: auto

knitr:
  opts_chunk:
    collapse: true
    comment: "#>"
    R.options:
      knitr.graphics.auto_pdf: true
