project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!_*.qmd"

website:
  title: "Regression Models for Epidemiology"
  site-url: https://d-morrison.github.io/rme/
  description: "Lecture notes for Epidemiology 204: Quantitative Epidemiology III (Statistical Models)"
  page-footer:
    left:
      - text: "Copyright 2024, Douglas Ezra Morrison"
  back-to-top-navigation: true
  page-navigation: true
  reader-mode: true
  repo-url: https://github.com/d-morrison/rme
  repo-actions: [edit, issue, source]
  google-analytics: "G-VS314RJ2KP"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Chapters"
        menu:
          - text: "Introduction to GLMs"
            href: Intro-to-GLMs.qmd
          - text: "---"
          - text: "Linear Models Overview"
            href: Linear-models-overview.qmd
          - text: "Logistic Regression"
            href: logistic-regression.qmd
          - text: "Count Regression"
            href: count-regression.qmd
          - text: "Multilevel Models"
            href: intro-multilevel-models.qmd
          - text: "---"
          - text: "Introduction to Survival Analysis"
            href: intro-to-survival-analysis.qmd
          - text: "Proportional Hazards Models"
            href: proportional-hazards-models.qmd
          - text: "Parametric Survival Models"
            href: parametric-survival-models.qmd
          - text: "---"
          - text: "Top Ten Concepts"
            href: top-ten-concepts.qmd
      - text: "Appendices"
        menu:
          - text: "Math Prerequisites"
            href: math-prereqs.qmd
          - text: "Probability"
            href: probability.qmd
          - text: "Estimation"
            href: estimation.qmd
          - text: "Inference"
            href: inference.qmd
          - text: "Introduction to MLEs"
            href: intro-MLEs.qmd
          - text: "Introduction to Bayesian Statistics"
            href: intro-bayes.qmd
          - text: "Common Mistakes"
            href: common-mistakes.qmd
          - text: "Notation"
            href: notation.qmd
          - text: "Introduction to R"
            href: intro-to-R.qmd
          - text: "Midterm Formula Sheet"
            href: midterm-formula-sheet.qmd
      - text: "References"
        href: references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    toc-location: right
    toc-depth: 3
    code-fold: true
    code-tools: true
    code-link: true
    code-summary: "Show R code"
    css: custom.scss
    highlight-style: pygments
    lightbox: true
    link-external-icon: true
    embed-resources: false
    fig-cap-location: top
    html-math-method: mathjax
    number-sections: true
    number-depth: 3
    df-print: paged
    date: last-modified
    date-format: "[Last modified:] YYYY-MM-DD: H:mm:ss (z)"
    subject: "Epidemiology 204"
  revealjs:
    lightbox: true
    theme: dark
    embed-resources: true
    fig-cap-location: top
    html-math-method: mathjax
    smaller: true
    number-sections: true
    progress: true
    incremental: false
    df-print: paged
    number-depth: 2
    slide-number: true
    shift-heading-level-by: -1
    slide-level: 2
    scrollable: true
    echo: true
    margin: 0.0
    code-fold: true
    code-link: true
    code-summary: "[R code]"
    auto-stretch: true
    fig-height: 5
    fig-width: 7
  pdf:
    geometry:
      - top=15mm
      - bottom=20mm
    keep-md: false
    keep-tex: false
    toc: true
    fig-pos: "H"
    toc-title: Contents
    df-print: tibble
    links-as-notes: true
    documentclass: article
    colorlinks: true
    number-sections: true
    number-depth: 3

comments:
  hypothesis:
    theme: clean
    openSidebar: false
    enableExperimentalNewNoteButton: true
