project:
  output-dir: _handouts
  render:
    - "index.qmd"
    - "Intro-to-GLMs.qmd"
    - "Linear-models-overview.qmd"
    - "logistic-regression.qmd"
    - "count-regression.qmd"
    - "intro-multilevel-models.qmd"
    - "intro-to-survival-analysis.qmd"
    - "proportional-hazards-models.qmd"
    - "parametric-survival-models.qmd"
    - "top-ten-concepts.qmd"
    - "math-prereqs.qmd"
    - "probability.qmd"
    - "estimation.qmd"
    - "inference.qmd"
    - "intro-MLEs.qmd"
    - "intro-bayes.qmd"
    - "common-mistakes.qmd"
    - "notation.qmd"
    - "intro-to-R.qmd"
    - "midterm-formula-sheet.qmd"

format:
  pdf:
    geometry:
      - top=15mm
      - bottom=20mm
    keep-md: false
    keep-tex: false
    toc: true
    fig-pos: "H"
    toc-title: Contents
    df-print: tibble
    links-as-notes: true
    documentclass: article
    colorlinks: true
    number-sections: true
    number-depth: 3

execute:
  warning: false
  message: false
  cache: false
  freeze: auto

knitr:
  opts_chunk:
    collapse: true
    comment: "#>"
